
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import LoTECCFileChooserFilters.SecureFilter;
import javax.swing.filechooser.FileFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class MMenu extends javax.swing.JFrame {
    public MMenu() {
        initComponents();

       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        ViewButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LoTE Character Creator");
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jButton1.setText("Stwórz Postać");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(940, 280, 120, 50);

        jButton2.setText("Edytuj Postać");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(940, 340, 120, 50);

        jButton4.setText("Wyjdź");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(940, 460, 120, 50);

        ViewButton.setText("Przeglądaj");
        ViewButton.setMaximumSize(new java.awt.Dimension(99, 23));
        ViewButton.setMinimumSize(new java.awt.Dimension(99, 23));
        ViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ViewButton);
        ViewButton.setBounds(940, 400, 120, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\LoTECC\\src\\prostokat1.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jLabel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        new giveName().setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
           int decision=JOptionPane.showConfirmDialog(null, "Czy na pewno chcesz wyjść?", "Select an Option...",
	JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
                if(decision==0)
                {System.exit(0);}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        final JFileChooser LoadFile = new JFileChooser();
        LoadFile.setAcceptAllFileFilterUsed(false);
        FileFilter propertiesFilter = new SecureFilter(".properties", "Wszystkie postaci");        
        LoadFile.addChoosableFileFilter(propertiesFilter);
        LoadFile.setCurrentDirectory(new File(System.getProperty("user.dir")));
        LoadFile.showOpenDialog(rootPane);
        Properties p = new Properties();
        try {
            
           InputStream is = new FileInputStream(LoadFile.getSelectedFile());
           p.load(is);

        } catch (FileNotFoundException ex) {
            System.out.println(ex);
            Logger.getLogger(MMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            System.out.println(ex);
            Logger.getLogger(MMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        String newname=p.getProperty("name");
        System.out.print(p.getProperty("name"));
        Character c = new Character();
        c.setVisible(true);
        c.LateCharacter(p.getProperty("name"),p.getProperty("race"),p.getProperty("strength"),p.getProperty("dexterity"),p.getProperty("speed"),p.getProperty("endurance"),p.getProperty("smarts"),
            p.getProperty("psyche"),p.getProperty("senses"),p.getProperty("movement"),p.getProperty("health"),p.getProperty("talentPD"),p.getProperty("sanity"),p.getProperty("deckOfFortune"),
            p.getProperty("actionPoints"),p.getProperty("durability"),p.getProperty("maxPD"),p.getProperty("mana"),p.getProperty("dmgreduction"));
        this.dispose();
        
       // new Character(newname).setVisible(true);
          /*  new Character(p.getProperty("name"),p.getProperty("race"),p.getProperty("strength"),p.getProperty("dexterity"),p.getProperty("speed"),p.getProperty("endurance"),p.getProperty("smarts"),
            p.getProperty("psyche"),p.getProperty("senses"),p.getProperty("movement"),p.getProperty("health"),p.getProperty("talentPD"),p.getProperty("sanity"),p.getProperty("deckOfFortune"),
            p.getProperty("actionPoints"),p.getProperty("durability"),p.getProperty("maxPD"),p.getProperty("mana"),p.getProperty("dmgreduction")).setVisible(true); */
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewButtonActionPerformed
        new Filter().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ViewButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ViewButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
